import { initPanel } from "./panel";
import { initToc } from "./toc";
import {
  buildDrillUrl, readBitParam, initDrillBreadcrumb,
  loadSnapshot, saveSnapshot, clearSnapshot,
} from "./drillContext";
import { renderDecoderScene } from "./scenes/decoderScene";

// 4-to-1 MUX: 4 data inputs + 2-bit select → 1 output.
//   out = in[s1*2 + s0]
//
// Internally: a 2-to-4 decoder (s1, s0 → sel0..sel3 one-hot) feeds 4
// AND gates (each ANDs one input with its corresponding sel line),
// then a 4-input OR collapses them all into a single output.

type Bit = 0 | 1;

const SVG_NS = 'http://www.w3.org/2000/svg';

const btnIn3   = document.getElementById('btnIn3')   as HTMLButtonElement;
const btnIn2   = document.getElementById('btnIn2')   as HTMLButtonElement;
const btnIn1   = document.getElementById('btnIn1')   as HTMLButtonElement;
const btnIn0   = document.getElementById('btnIn0')   as HTMLButtonElement;
const btnS1    = document.getElementById('btnS1')    as HTMLButtonElement;
const btnS0    = document.getElementById('btnS0')    as HTMLButtonElement;
const btnReset = document.getElementById('btnReset') as HTMLButtonElement;
const svg      = document.getElementById('mux')      as unknown as SVGSVGElement;
const selBits  = document.getElementById('selBits') as HTMLElement;
const selDec   = document.getElementById('selDec')  as HTMLElement;
const pickedLabel = document.getElementById('pickedLabel') as HTMLElement;
const outBit   = document.getElementById('outBit')  as HTMLElement;

type MuxSnap = { ins: Bit[]; s1: Bit; s0: Bit };
const SNAP_KEY = 'mux';
const _snap = loadSnapshot<MuxSnap>(SNAP_KEY);
const ins: Bit[] = [
  readBitParam('in0', _snap?.ins?.[0] ?? 0),
  readBitParam('in1', _snap?.ins?.[1] ?? 0),
  readBitParam('in2', _snap?.ins?.[2] ?? 0),
  readBitParam('in3', _snap?.ins?.[3] ?? 0),
];
let s1: Bit = readBitParam('s1', _snap?.s1 ?? 0);
let s0: Bit = readBitParam('s0', _snap?.s0 ?? 0);

// Gates (AND D-shapes, OR shield) are drawn as static logic-symbol
// <path> elements in the HTML — their truth tables are trivial.
//
// The decoder block, however, hovers to reveal a real preview of its
// internals. That preview is generated by `renderDecoderScene` (the
// same function `/decoder.html` uses for its full-size view), just
// scaled to the embedded box. Single source of truth = layer-10
// wireframe → `src/scenes/decoderScene.ts` → both views.
const decoderDetail = document.getElementById('decoderDetail');
if (decoderDetail) {
  // The decoder box in the MUX SVG: x∈[560, 880], y∈[40, 280] (= 4×3 wu world).
  decoderDetail.appendChild(renderDecoderScene(
    { x: 560, y: 40, w: 320, h: 240 },
    { idPrefix: 'dp', showPins: false, pinRadius: 3 },
  ));
}

// Wire pulse overlays
const wires = Array.from(svg.querySelectorAll<SVGPolylineElement>('.wire'));
const pulseFor = new Map<SVGPolylineElement, SVGPolylineElement>();
for (const w of wires) {
  const p = document.createElementNS(SVG_NS, 'polyline');
  p.setAttribute('class', 'pulse');
  p.setAttribute('points', w.getAttribute('points') || '');
  const net = w.getAttribute('data-net');
  if (net) p.setAttribute('data-net', net);
  p.setAttribute('data-on', w.getAttribute('data-on') || '0');
  w.insertAdjacentElement('afterend', p);
  pulseFor.set(w, p);
}

function setNet(net: string, on: Bit) {
  svg.querySelectorAll<SVGPolylineElement>(`.wire[data-net="${net}"]`).forEach((el) => {
    el.setAttribute('data-on', String(on));
    const p = pulseFor.get(el);
    if (p) p.setAttribute('data-on', String(on));
  });
}
function setPin(id: string, on: Bit) {
  document.getElementById(id)?.setAttribute('data-on', String(on));
}
function setBtn(btn: HTMLButtonElement, label: string, value: Bit) {
  btn.setAttribute('data-on', String(value));
  btn.textContent = `${label} ${value}`;
}

function render() {
  // Decoder logic — 4 one-hot lines
  const selIdx = s1 * 2 + s0;
  const sel: Bit[] = [0, 0, 0, 0];
  sel[selIdx] = 1;

  // Per-AND output = in[n] & sel[n]
  const andOut: Bit[] = [
    (ins[0] & sel[0]) as Bit,
    (ins[1] & sel[1]) as Bit,
    (ins[2] & sel[2]) as Bit,
    (ins[3] & sel[3]) as Bit,
  ];
  // OR collapses them
  const out: Bit = (andOut[0] | andOut[1] | andOut[2] | andOut[3]) as Bit;

  // Wire highlights
  setNet('s1', s1);
  setNet('s0', s0);
  setNet('in3', ins[3]);
  setNet('in2', ins[2]);
  setNet('in1', ins[1]);
  setNet('in0', ins[0]);
  setNet('sel3', sel[3]);
  setNet('sel2', sel[2]);
  setNet('sel1', sel[1]);
  setNet('sel0', sel[0]);
  setNet('andOut3', andOut[3]);
  setNet('andOut2', andOut[2]);
  setNet('andOut1', andOut[1]);
  setNet('andOut0', andOut[0]);
  setNet('out', out);

  // Gate body glows
  document.getElementById('gAnd0')!.setAttribute('data-on', String(andOut[0]));
  document.getElementById('gAnd1')!.setAttribute('data-on', String(andOut[1]));
  document.getElementById('gAnd2')!.setAttribute('data-on', String(andOut[2]));
  document.getElementById('gAnd3')!.setAttribute('data-on', String(andOut[3]));
  document.getElementById('gOr')!.setAttribute('data-on', String(out));
  document.getElementById('gDecoder')!.setAttribute('data-on', '1'); // always active

  // Decoder hover-preview state: every gate body and wire net in the
  // mini decoder maps 1:1 to the real /decoder.html, so we drive it
  // with the same logic — inverter outputs are ~s_n, ANDs follow sel[].
  const na1: Bit = (s1 === 0 ? 1 : 0) as Bit;
  const na0: Bit = (s0 === 0 ? 1 : 0) as Bit;
  if (decoderDetail) {
    // Gate bodies (renderer prefixed IDs with 'dp')
    decoderDetail.querySelector('#dpInvA1')?.setAttribute('data-on', String(na1));
    decoderDetail.querySelector('#dpInvA0')?.setAttribute('data-on', String(na0));
    decoderDetail.querySelector('#dpAnd3')?.setAttribute('data-on', String(sel[3]));
    decoderDetail.querySelector('#dpAnd2')?.setAttribute('data-on', String(sel[2]));
    decoderDetail.querySelector('#dpAnd1')?.setAttribute('data-on', String(sel[1]));
    decoderDetail.querySelector('#dpAnd0')?.setAttribute('data-on', String(sel[0]));
    // Wires by net — every polyline rendered by the scene has the same data-net
    // values as the real decoder, so the lighting rules are identical.
    const setPreviewNet = (net: string, on: Bit) => {
      decoderDetail.querySelectorAll<SVGPolylineElement>(`.wire[data-net="${net}"]`)
        .forEach((w) => w.setAttribute('data-on', String(on)));
    };
    setPreviewNet('a1',    s1);
    setPreviewNet('a0',    s0);
    setPreviewNet('a1bar', na1);
    setPreviewNet('a0bar', na0);
    setPreviewNet('EN',    1);
    setPreviewNet('sel3',  sel[3]);
    setPreviewNet('sel2',  sel[2]);
    setPreviewNet('sel1',  sel[1]);
    setPreviewNet('sel0',  sel[0]);
  }

  // Pins
  setPin('pinIn0', ins[0]); setPin('pinIn1', ins[1]);
  setPin('pinIn2', ins[2]); setPin('pinIn3', ins[3]);
  setPin('pinS0', s0);      setPin('pinS1', s1);
  setPin('pinOut', out);

  // Buttons
  setBtn(btnIn0, 'in0', ins[0]); setBtn(btnIn1, 'in1', ins[1]);
  setBtn(btnIn2, 'in2', ins[2]); setBtn(btnIn3, 'in3', ins[3]);
  setBtn(btnS0, 's0', s0);       setBtn(btnS1, 's1', s1);

  // Readouts
  selBits.textContent = `${s1}${s0}`;
  selDec.textContent = `(${selIdx})`;
  pickedLabel.textContent = `in${selIdx}`;
  outBit.textContent = String(out);
}

function persist() {
  saveSnapshot<MuxSnap>(SNAP_KEY, { ins: [...ins] as Bit[], s1, s0 });
}

btnIn0.addEventListener('click', () => { ins[0] = ins[0] === 0 ? 1 : 0; render(); persist(); });
btnIn1.addEventListener('click', () => { ins[1] = ins[1] === 0 ? 1 : 0; render(); persist(); });
btnIn2.addEventListener('click', () => { ins[2] = ins[2] === 0 ? 1 : 0; render(); persist(); });
btnIn3.addEventListener('click', () => { ins[3] = ins[3] === 0 ? 1 : 0; render(); persist(); });
btnS0.addEventListener('click', () => { s0 = s0 === 0 ? 1 : 0; render(); persist(); });
btnS1.addEventListener('click', () => { s1 = s1 === 0 ? 1 : 0; render(); persist(); });
btnReset.addEventListener('click', () => {
  ins[0] = 0; ins[1] = 0; ins[2] = 0; ins[3] = 0;
  s0 = 0; s1 = 0;
  clearSnapshot(SNAP_KEY);
  render();
});

// ── Drill-down: clicking the decoder block goes to /decoder.html ─────
document.getElementById('slot-decoder')?.addEventListener('click', () => {
  window.location.assign(buildDrillUrl('/decoder.html', {
    from: 'mux', which: 'select-decoder', a1: s1, a0: s0, EN: 1,
  }));
});

render();

// Walkthrough nav
const steps = Array.from(document.querySelectorAll<HTMLElement>('.step'));
const stepPrev = document.getElementById('stepPrev') as HTMLButtonElement;
const stepNext = document.getElementById('stepNext') as HTMLButtonElement;
const stepNum  = document.getElementById('stepNum')!;
const stepCount = document.getElementById('stepCount')!;
stepCount.textContent = ` / ${steps.length}`;
let currentStep = 0;
function showStep(i: number) {
  currentStep = Math.max(0, Math.min(steps.length - 1, i));
  steps.forEach((s, idx) => s.toggleAttribute('hidden', idx !== currentStep));
  stepNum.textContent = String(currentStep + 1);
  stepPrev.disabled = currentStep === 0;
  stepNext.disabled = currentStep === steps.length - 1;
}
stepPrev.addEventListener('click', () => showStep(currentStep - 1));
stepNext.addEventListener('click', () => showStep(currentStep + 1));
showStep(0);

initPanel();
initToc();
initDrillBreadcrumb();
